##script (Python) "sdf"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=
##title=
##
request = container.REQUEST
RESPONSE =  request.RESPONSE


ddc = [
    {'code':'000', 'description':'Informatik, Informationswissenschaft, allgemeine Werke'},
    {'code':'004', 'description':'Informatik'},
    {'code':'010', 'description':'Bibliografien'},
    {'code':'020', 'description':'Bibliotheks- und Informationswissenschaft'},
    {'code':'030', 'description':'Enzyklopädien'},
    {'code':'050', 'description':'Zeitschriften, fortlaufende Sammelwerke'},
    {'code':'060', 'description':'Organisationen, Museumswissenschaft'},
    {'code':'070', 'description':'Nachrichtenmedien, Journalismus, Verlagswesen'},
    {'code':'080', 'description':'Allgemeine Sammelwerke'},
    {'code':'090', 'description':'Handschriften, seltene Bücher'},
    {'code':'100', 'description':'Philosophie und Psychologie'},
    {'code':'130', 'description':'Parapsychologie, Okkultismus'},
    {'code':'150', 'description':'Psychologie'},
    {'code':'200', 'description':'Religion'},
    {'code':'220', 'description':'Bibel'},
    {'code':'230', 'description':'Theologie, Christentum'},
    {'code':'290', 'description':'Andere Religionen'},
    {'code':'300', 'description':'Sozialwissenschaften'},
    {'code':'310', 'description':'Statistik'},
    {'code':'320', 'description':'Politik'},
    {'code':'330', 'description':'Wirtschaft'},
    {'code':'340', 'description':'Recht'},
    {'code':'350', 'description':'Öffentliche Verwaltung'},
    {'code':'355', 'description':'Militär'},
    {'code':'360', 'description':'Soziale Probleme, Sozialarbeit'},
    {'code':'370', 'description':'Erziehung, Schul- und Bildungswesen'},
    {'code':'380', 'description':'Handel, Kommunikation, Verkehr'},
    {'code':'390', 'description':'Ethnologie'},
    {'code':'400', 'description':'Sprache'},
    {'code':'420', 'description':'Englisch'},
    {'code':'430', 'description':'Deutsch'},
    {'code':'439', 'description':'Andere germanische Sprachen'},
    {'code':'440', 'description':'Französisch, romanische Sprachen allgemein'},
    {'code':'450', 'description':'Italienisch, Rumänisch, Rätoromanisch'},
    {'code':'460', 'description':'Spanisch, Portugiesisch'},
    {'code':'470', 'description':'Latein'},
    {'code':'480', 'description':'Griechisch'},
    {'code':'490', 'description':'Andere Sprachen'},
    {'code':'500', 'description':'Naturwissenschaften und Mathematik'},
    {'code':'510', 'description':'Mathematik'},
    {'code':'520', 'description':'Astronomie, Kartographie'},
    {'code':'530', 'description':'Physik'},
    {'code':'540', 'description':'Chemie'},
    {'code':'550', 'description':'Geowissenschaften'},
    {'code':'560', 'description':'Paläontologie'},
    {'code':'570', 'description':'Biowissenschaften, Biologie'},
    {'code':'580', 'description':'Pflanzen (Botanik)'},
    {'code':'590', 'description':'Tiere (Zoologie)'},
    {'code':'600', 'description':'Technik, Medizin, angewandte Wissenschaften'},
    {'code':'610', 'description':'Medizin, Gesundheit'},
    {'code':'620', 'description':'Ingenieurwissenschaften'},
    {'code':'630', 'description':'Landwirtschaft, Veterinärmedizin'},
    {'code':'640', 'description':'Hauswirtschaft'},
    {'code':'650', 'description':'Management'},
    {'code':'660', 'description':'Technische Chemie'},
    {'code':'670', 'description':'Industrielle Fertigung'},
    {'code':'690', 'description':'Hausbau, Bauhandwerk'},
    {'code':'700', 'description':'Künste und Unterhaltung'},
    {'code':'710', 'description':'Landschaftsgestaltung, Raumplanung'},
    {'code':'720', 'description':'Architektur'},
    {'code':'730', 'description':'Plastik, Numismatik, Keramik, Metallkunst'},
    {'code':'740', 'description':'Zeichnung, Kunsthandwerk'},
    {'code':'741.5', 'description':'Comics, Cartoons, Karikaturen'},
    {'code':'750', 'description':'Malerei'},
    {'code':'760', 'description':'Grafische Verfahren, Drucke'},
    {'code':'770', 'description':'Fotografie, Computerkunst'},
    {'code':'780', 'description':'Musik'},
    {'code':'790', 'description':'Freizeitgestaltung, Darstellende Kunst'},
    {'code':'791', 'description':'Öffentliche Darbietungen, Film, Rundfunk'},
    {'code':'792', 'description':'Theater, Tanz'},
    {'code':'793', 'description':'Spiel'},
    {'code':'796', 'description':'Sport'},
    {'code':'800', 'description':'Literatur'},
    {'code':'810', 'description':'Englische Literatur Amerikas'},
    {'code':'820', 'description':'Englische Literatur'},
    {'code':'830', 'description':'Deutsche Literatur'},
    {'code':'839', 'description':'Literatur in anderen germanischen Sprachen'},
    {'code':'840', 'description':'Französische Literatur'},
    {'code':'850', 'description':'Italienische, rumänische, rätoromanische Literatur'},
    {'code':'860', 'description':'Spanische und portugiesische Literatur'},
    {'code':'870', 'description':'Lateinische Literatur'},
    {'code':'880', 'description':'Griechische Literatur'},
    {'code':'890', 'description':'Literatur in anderen Sprachen'},
    {'code':'900', 'description':'Geschichte und Geografie'},
    {'code':'910', 'description':'Geografie, Reisen'},
    {'code':'914.3', 'description':'Landeskunde Deutschlands'},
    {'code':'920', 'description':'Biografie, Genealogie, Heraldik'},
    {'code':'930', 'description':'Alte Geschichte, Archäologie'},
    {'code':'940', 'description':'Geschichte Europas'},
    {'code':'943', 'description':'Geschichte Deutschlands'},
    {'code':'950', 'description':'Geschichte Asiens'},
    {'code':'960', 'description':'Geschichte Afrikas'},
    {'code':'970', 'description':'Geschichte Nordamerikas'},
    {'code':'980', 'description':'Geschichte Südamerikas'},
    {'code':'990', 'description':'Geschichte der übrigen Welt'}
]

return ddc
